<?php

use Illuminate\Database\Seeder;

class CurrencyTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('currencies')->truncate();
        $statement = "INSERT INTO `currencies` (`id`, `country`, `currency`, `code`, `symbol`) VALUES
        (1, 'Albaniaa', 'Leke', 'ALL', 'Lek'),
        (2, 'America', 'Dollars', 'USD', '$'),
        (3, 'Afghanistan', 'Afghanis', 'AFN', '؋'),
        (4, 'Argentina', 'Pesos', 'ARS', '$'),
        (5, 'Aruba', 'Guilders', 'AWG', 'ƒ'),
        (6, 'Australia', 'Dollars', 'AUD', '$'),
        (7, 'Azerbaijan', 'New Manats', 'AZN', 'ман'),
        (8, 'Bahamas', 'Dollars', 'BSD', '$'),
        (9, 'Bangladesh', 'Taka', 'BDT', '৳'),
        (10, 'Barbados', 'Dollars', 'BBD', '$'),
        (11, 'Belarus', 'Rubles', 'BYR', 'p.'),
        (12, 'Belgium', 'Euro', 'EUR', '€'),
        (13, 'Beliz', 'Dollars', 'BZD', 'BZ$'),
        (14, 'Bermuda', 'Dollars', 'BMD', '$'),
        (15, 'Bolivia', 'Bolivianos', 'BOB', 'b$'),
        (16, 'Bosnia and Herzegovina', 'Convertible Marka', 'BAM', 'KM'),
        (17, 'Botswana', 'Pula', 'BWP', 'P'),
        (18, 'Bulgaria', 'Leva', 'BGN', 'лв'),
        (19, 'Brazil', 'Reais', 'BRL', 'R$'),
        (20, 'Britain (United Kingdom)', 'Pounds', 'GBP', '£'),
        (21, 'Brunei Darussalam', 'Dollars', 'BND', '$'),
        (22, 'Cambodia', 'Riels', 'KHR', '៛'),
        (23, 'Canada', 'Dollars', 'CAD', '$'),
        (24, 'Cayman Islands', 'Dollars', 'KYD', '$'),
        (25, 'Chile', 'Pesos', 'CLP', '$'),
        (26, 'China', 'Yuan Renminbi', 'CNY', '¥'),
        (27, 'Colombia', 'Pesos', 'COP', '$'),
        (28, 'Costa Rica', 'Colón', 'CRC', '₡'),
        (29, 'Croatia', 'Kuna', 'HRK', 'kn'),
        (30, 'Cuba', 'Pesos', 'CUP', '₱'),
        (31, 'Cyprus', 'Euro', 'EUR', '€'),
        (32, 'Czech Republic', 'Koruny', 'CZK', 'Kč'),
        (33, 'Denmark', 'Kroner', 'DKK', 'kr'),
        (34, 'Dominican Republic', 'Pesos', 'DOP ', 'RD$'),
        (35, 'East Caribbean', 'Dollars', 'XCD', '$'),
        (36, 'Egypt', 'Pounds', 'EGP', '£'),
        (37, 'El Salvador', 'Colones', 'SVC', '$'),
        (38, 'England (United Kingdom)', 'Pounds', 'GBP', '£'),
        (39, 'Euro', 'Euro', 'EUR', '€'),
        (40, 'Falkland Islands', 'Pounds', 'FKP', '£'),
        (41, 'Fiji', 'Dollars', 'FJD', '$'),
        (42, 'France', 'Euro', 'EUR', '€'),
        (43, 'Ghana', 'Cedis', 'GHC', '¢'),
        (44, 'Gibraltar', 'Pounds', 'GIP', '£'),
        (45, 'Greece', 'Euro', 'EUR', '€'),
        (46, 'Guatemala', 'Quetzales', 'GTQ', 'Q'),
        (47, 'Guernsey', 'Pounds', 'GGP', '£'),
        (48, 'Guyana', 'Dollars', 'GYD', '$'),
        (49, 'Holland (Netherlands)', 'Euro', 'EUR', '€'),
        (50, 'Honduras', 'Lempiras', 'HNL', 'L'),
        (51, 'Hong Kong', 'Dollars', 'HKD', '$'),
        (52, 'Hungary', 'Forint', 'HUF', 'Ft'),
        (53, 'Iceland', 'Kronur', 'ISK', 'kr'),
        (54, 'India', 'Rupees', 'INR', 'Rp.'),
        (55, 'Indonesia', 'Rupiahs', 'IDR', 'Rp.'),
        (56, 'Iran', 'Rials', 'IRR', '﷼'),
        (57, 'Ireland', 'Euro', 'EUR', '€'),
        (58, 'Isle of Man', 'Pounds', 'IMP', '£'),
        (59, 'Israel', 'New Shekels', 'ILS', '₪'),
        (60, 'Italy', 'Euro', 'EUR', '€'),
        (61, 'Jamaica', 'Dollars', 'JMD', 'J$'),
        (62, 'Japan', 'Yen', 'JPY', '¥'),
        (63, 'Jersey', 'Pounds', 'JEP', '£'),
        (64, 'Kazakhstan', 'Tenge', 'KZT', 'лв'),
        (65, 'Korea (North)', 'Won', 'KPW', '₩'),
        (66, 'Korea (South)', 'Won', 'KRW', '₩'),
        (67, 'Kyrgyzstan', 'Soms', 'KGS', 'лв'),
        (68, 'Laos', 'Kips', 'LAK', '₭'),
        (69, 'Latvia', 'Lati', 'LVL', 'Ls'),
        (70, 'Lebanon', 'Pounds', 'LBP', '£'),
        (71, 'Liberia', 'Dollars', 'LRD', '$'),
        (72, 'Liechtenstein', 'Switzerland Francs', 'CHF', 'CHF'),
        (73, 'Lithuania', 'Litai', 'LTL', 'Lt'),
        (74, 'Luxembourg', 'Euro', 'EUR', '€'),
        (75, 'Macedonia', 'Denars', 'MKD', 'ден'),
        (76, 'Malaysia', 'Ringgits', 'MYR', 'RM'),
        (77, 'Malta', 'Euro', 'EUR', '€'),
        (78, 'Mauritius', 'Rupees', 'MUR', '₨'),
        (79, 'Mexico', 'Pesos', 'MXN', '$'),
        (80, 'Mongolia', 'Tugriks', 'MNT', '₮'),
        (81, 'Mozambique', 'Meticais', 'MZN', 'MT'),
        (82, 'Namibia', 'Dollars', 'NAD', '$'),
        (83, 'Nepal', 'Rupees', 'NPR', '₨'),
        (84, 'Netherlands Antilles', 'Guilders', 'ANG', 'ƒ'),
        (85, 'Netherlands', 'Euro', 'EUR', '€'),
        (86, 'New Zealand', 'Dollars', 'NZD', '$'),
        (87, 'Nicaragua', 'Cordobas', 'NIO', 'C$'),
        (88, 'Nigeria', 'Nairas', 'NGN', '₦'),
        (89, 'North Korea', 'Won', 'KPW', '₩'),
        (90, 'Norway', 'Krone', 'NOK', 'kr'),
        (91, 'Oman', 'Rials', 'OMR', '﷼'),
        (92, 'Pakistan', 'Rupees', 'PKR', '₨'),
        (93, 'Panama', 'Balboa', 'PAB', 'B/.'),
        (94, 'Paraguay', 'Guarani', 'PYG', 'Gs'),
        (95, 'Peru', 'Nuevos Soles', 'PEN', 'S/.'),
        (96, 'Philippines', 'Pesos', 'PHP', 'Php'),
        (97, 'Poland', 'Zlotych', 'PLN', 'zł'),
        (98, 'Qatar', 'Rials', 'QAR', '﷼'),
        (99, 'Romania', 'New Lei', 'RON', 'lei'),
        (100, 'Russia', 'Rubles', 'RUB', 'руб'),
        (101, 'Saint Helena', 'Pounds', 'SHP', '£'),
        (102, 'Saudi Arabia', 'Riyals', 'SAR', '﷼'),
        (103, 'Serbia', 'Dinars', 'RSD', 'Дин.'),
        (104, 'Seychelles', 'Rupees', 'SCR', '₨'),
        (105, 'Singapore', 'Dollars', 'SGD', '$'),
        (106, 'Slovenia', 'Euro', 'EUR', '€'),
        (107, 'Solomon Islands', 'Dollars', 'SBD', '$'),
        (108, 'Somalia', 'Shillings', 'SOS', 'S'),
        (109, 'South Africa', 'Rand', 'ZAR', 'R'),
        (110, 'South Korea', 'Won', 'KRW', '₩'),
        (111, 'Spain', 'Euro', 'EUR', '€'),
        (112, 'Sri Lanka', 'Rupees', 'LKR', '₨'),
        (113, 'Sweden', 'Kronor', 'SEK', 'kr'),
        (114, 'Switzerland', 'Francs', 'CHF', 'CHF'),
        (115, 'Suriname', 'Dollars', 'SRD', '$'),
        (116, 'Syria', 'Pounds', 'SYP', '£'),
        (117, 'Taiwan', 'New Dollars', 'TWD', 'NT$'),
        (118, 'Thailand', 'Baht', 'THB', '฿'),
        (119, 'Trinidad and Tobago', 'Dollars', 'TTD', 'TT$'),
        (120, 'Turkey', 'Lira', 'TRY', 'TL'),
        (121, 'Turkey', 'Liras', 'TRL', '£'),
        (122, 'Tuvalu', 'Dollars', 'TVD', '$'),
        (123, 'Ukraine', 'Hryvnia', 'UAH', '₴'),
        (124, 'United Kingdom', 'Pounds', 'GBP', '£'),
        (125, 'United States of America', 'Dollars', 'USD', '$'),
        (126, 'Uruguay', 'Pesos', 'UYU', 'U$'),
        (127, 'Uzbekistan', 'Sums', 'UZS', 'лв'),
        (128, 'Vatican City', 'Euro', 'EUR', '€'),
        (129, 'Venezuela', 'Bolivares Fuertes', 'VEF', 'Bs'),
        (130, 'Vietnam', 'Dong', 'VND', '₫'),
        (131, 'Yemen', 'Rials', 'YER', '﷼'),
        (132, 'Zimbabwe', 'Zimbabwe Dollars', 'ZWD', 'Z$')";
        DB::unprepared($statement);
    }
}
